project:
  type: website
  output-dir: docs

website:
  title: "Fendi Tsim"
  search: false
  favicon: img/logo.png
  navbar:
    background: "#FFFFFF"
    foreground: "#5CB6BD"
    right:
      - text: "About Me"
        href: resume/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Writings"
        href: writings/index.qmd
      - text: "Gallery"
        href: gallery/index.qmd
    
  page-footer: 
    left: "© 2024 Fendi Tsim" 
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: true
    section-divs: true

editor: visual