---
pagetitle: "Research"
format:
  html:
    include-in-header:
      text: |
        <style>
        details {
          text-align: justify;
        }
        </style>
---

## Research

<details close>
<summary class="collapsible-header">Preprints</summary>
<div class="collapsible-content">

::::::: paper-box
::: paper-title
[SCAN: A Decision-Making Framework for Task Assignment with Generative AI](https://osf.io/preprints/psyarxiv/g5fd8_v1)
:::

::: paper-year
2025
:::

::: paper-authors
with [Alina Gutoreva](https://scholar.google.com/citations?user=bjfbYmAAAAAJ&hl=en&oi=ao)
:::

::: paper-description
We introduce SCAN-a human-centric decision-making framework to facilitate learners for an effective task assignment with Generative AI based on psychology theories such as Vygotsky’s Zone of Proximal Development and Metacognition. In SCAN, we systematize and formalize AI-human interaction by introducing a task identification approach with four ''sub-zones'': Substitute, Complement, Aid, and Non-negotiable. After describing the four sub-zones, we demonstrate how SCAN framework can be applied for knowledge workers in the workplace and students in the education to "scan" their use of Generative AI. We then discuss how such framework can be related to cognitive offloading, sycophancy, three decision making modes in human-AI interactions(automation, augmentation, and collaboration), as well as future of work such as upskilling and deskilling. We propose that SCAN offers a great starting point before discussing whether Generative AI complements or replaces our abilities when completing a task, with a general objective of sustaining lifelong learning, and a specific goal of reaching hybrid intelligence.
:::
:::::::

</div>
</details>


<details close>
<summary class="collapsible-header">Working Papers / Manuscripts in Preparation</summary>
<div class="collapsible-content">

::::::: paper-box
::: paper-title
AI as Part of Self: Rethinking Human–AI Coordination, Cognition, and Identity
:::

::: paper-year
2025
:::

::: paper-authors
with [Alina Gutoreva](https://scholar.google.com/citations?user=bjfbYmAAAAAJ&hl=en&oi=ao)
:::

::: paper-description
The "AI as Part of Self" framework reconceptualizes AI not merely as a tool or agent but as an extension of human cognition.
:::
:::::::

::::::: paper-box
::: paper-title
CIA: A Prompt Framework Mitigating Sycophancy
:::

::: paper-year
2025
:::

::: paper-authors
with [Shantanu Sharma](https://orcid.org/0009-0008-8914-9544)
:::

::: paper-description
The CIA Framework is a structured approach designed to enhance interactions with Large Language Models (LLMs) where users can uncover deeper insights, identify biases, and arrive at more nuanced understandings of complex topics.
:::
:::::::

::::::: paper-box
::: paper-title
Division of Cognitive Labor
:::

::: paper-year
2025
:::

::: paper-authors
with [Alina Gutoreva](https://scholar.google.com/citations?user=bjfbYmAAAAAJ&hl=en&oi=ao)
:::

::: paper-description
:::
:::::::

</div>
</details>

<details close>
<summary class="collapsible-header">PhD Thesis</summary>
<div class="collapsible-content">

:::::::: paper-box
::: paper-title
[An experimental investigation of virtual bargaining in one-shot and repeated games](https://wrap.warwick.ac.uk/id/eprint/191656/1/WRAP_Theses_Tsim_2024.pdf)
:::

::: paper-year
2024
:::

::: paper-authors
with [Nick Chater](https://scholar.google.com/citations?user=pH1PDwYAAAAJ&hl=en&oi=ao), [Tigran Melkonyan](https://scholar.google.com/citations?user=VYLEK58AAAAJ&hl=en&oi=ao), [Hossam Zeitoun](https://scholar.google.com/citations?user=DUW5bD4AAAAJ&hl=en&oi=ao), and [Christoph Karl Becker](https://scholar.google.com/citations?user=o8UEz6kAAAAJ&hl=en&oi=ao)
:::

:::: paper-abstract
<details>

<summary>Abstract</summary>

::: paper-description
In this thesis, I aim to explain the existence of coordination without communication, a striking finding in studying interactive decision making in non-cooperative interactions. I apply, and test, Virtual Bargaining (henceforth VB), a recent theory of psychological commitment whereby agents choose based on tacit agreements formed via hypothetical negotiations.

The first part of this thesis investigates coordination in an adversarial, one-off interaction between an employer and a worker called the Inspection Game.

Chapter 2 investigates how varying inspection cost affects likelihood of noncompliance detection. When inspection is at substantially higher costs, Nash reasoning predicts no inspection, while VB predicts inspection is still possible, even when it is very costly to do so. We also investigate whether social norm might instead be potential cause to our finding and find no support for this hypothesis.

Extending the theory of VB, Chapter 3 discusses theoretically how an appearance of a bargaining procedure in an interaction, such as nonbinding, costless agreements, creates an asymmetry in bargaining power among agents, and thus often facilitates coordination. We discuss how this new approach to VB can be applied into other social interactions, helping to explain why unilateral, instead of bilateral, communication can lead to more coordination in an interaction.

Chapter 4 explores noncompliance prevention with unilateral, costless communication in the Inspection Game. We apply theoretical discussion from Chapter 3 with other psychological theories that explain sender’s promise-keeping behavior. We find that the effectiveness of unilateral communication for preventing noncompliance depends on who the sender in an employer-worker relationship is.

The second part of this thesis emphasizes on coordination in a dyadic, repeated interaction whereby “taking turns” is mutually beneficial. Chapter 5 explores reciprocation in the Alternation Game. This chapter also discusses other theories that explain pro-sociality in social interactions as potential drivers of reciprocation in this context.
:::

</details>

Individual Chapters:

-   Chapter 1: Introduction

-   Chapter 2: How does Inspection Cost affect choices in the Inspection Game?

    <details>

    <summary>Abstract</summary>

    ::: paper-description
    In an employer-worker relationship, an employer deploys an inspection, albeit costly to her, to detect, and discourage noncompliance behavior from her worker. It is natural to assume that the cost of paying to inspect has an impact on both roles. A well-developed approach in game theory, Nash reasoning, predicts that noncompliance cannot be discouraged entirely as both randomize their own choices for their own interests. Nash reasoning predicts that an employer is better off letting go of inspection once it becomes costlier than paying for worker’s wage. We posit our investigation of inspection cost in the Inspection Game, which models an adversarial interaction between an employer and her worker. We apply Virtual Bargaining (henceforth VB) that show worker’s non-compliance can be discouraged entirely, inspection can still be an effective deterrence when it becomes costlier, and when inspection loses its effectiveness entirely. We conduct two experiments with online participants: a choice experiment with three different inspection costs (Low, Medium and High) in which Nash reasoning and VB have the same predictions in Low and High conditions, but they diverge in the Medium condition; a norm elicitation experiment that explores the underlying norm by eliciting socially appropriate ratings of each action in our choice experiment. Surprisingly, our choice experiment reports that worker’s shirking probability does not vary across three conditions, and there is a negative association between inspection cost and employer’s inspecting probability. Interestingly, inspecting probability does not drop to zero in both Medium and High conditions, as Nash reasoning predicts. Our norm elicitation experiment reports that inspection and working are the most socially appropriate actions for both roles in most conditions, yet this cannot explain behaviors well in the choice experiment.
    :::

    </details>

-   Chapter 3: Virtual Bargaining with Asymmetric Bargaining Power

    <details>

    <summary>Abstract</summary>

    ::: paper-description
    We often see social interactions that multiple equilibria agents could coordinate on, and usually decision theories like Nash reasoning and Virtual Bargaining (henceforth VB) cannot provide a unique solution. A ‘refinement’ in selecting an equilibrium is necessary. A simple way for such refinement is to posit an interaction, as VB posits, as a bargaining situation among agents, and implement a procedure such as pre-play communication before they make a choice. This chapter proposes VB with Asymmetric Nash Bargaining Solution (henceforth ‘VB-ANBS’), a new approach of VB in attempting resolving coordination issues in interactions whereby a bargaining procedure is incremented in an interaction. VB-ANBS assumes that when a bargaining procedure is incremented, an agent’s bargaining power can be viewed as a confrontation between two types of psychological forces in social psychology: an agent’s ‘inducing’ force on the other agent, and a ‘resisting’ force of an agent when receiving an inducing force from others. An agent’s bargaining power is defined as the relative strength of her force in totality of forces acting on a given interaction at a given time. A’s bargaining power is then calculated as a ratio between her inducing force on B’s action and the sum of forces (her inducing force and B’s resisting force) in their interaction. This theoretical discussion first posits dyadic two-stage interactions whereby pre-play communication is present. VB-ANBS illustrates how a virtual bargain is in an interaction is influenced by the presence of a procedural asymmetry, for instance, how coordination can be achieved in mixed-motive games, how the ability to communicate in advance influences whether a potential threat can be implemented or avoided in a social interaction. Also, VB-ANBS provides insights as to why a bilateral communication, or unlimited conversation between a pair, might not lead to a virtual bargain in a context whereby their interests are not well-aligned. As power is relational among agents in a bargaining situation, VB-ANBS can explain differences in two common types of leadership (authoritarian and democratic), why the effect of a public announcement diminishes with group size as well as power distance, in terms of bargaining power.
    :::

    </details>

-   Chapter 4: Communication as Noncompliance Prevention in the Inspection Game

    <details>

    <summary>Abstract</summary>

    ::: paper-description
    In our daily lives, non-binding, costless statements are ubiquitous as an effective coordination device. In an employer-worker relationship, could such statements be an effective tool for an employer to prevent from, and thus discourage, noncompliance behavior from her worker? In this study, we posit our investigation on such adversarial interaction as the Inspection Game and discuss whether and how one-way communication can be an effective tool for noncompliance prevention. We apply three theories that explains why a sender keeps her promises: due to tacit agreements in an interaction when a bargaining procedure is present (VB with Asymmetric Nash Bargaining Solution), an aversion of anticipating that her recipient is let down when a promise is not kept (Guilt Aversion) and an aversion of a psychological cost when an inconsistency occurs between a promise and an action (Lying Aversion). We conduct an experiment with online participants: an Inspection Game with three different inspection costs (Low, Medium, and High) and two directions of communication (Downward and Upward) that theories have different predictions. Our study reports that talk is not ‘cheap’, and the direction of communication matters. Both employer and worker exploit the advantage of pre-play communication for personal interests. Interestingly, recipients behave differently from the prediction of a standard theoretical reasoning. We also explore the meaning of messages with a classification (promise, statement of intent, and empty talk), and show that most senders exploit fully the ability to send a pre-play promise or a statement of intent, and their recipients make a choice according to their messages. We conclude that one-way communication, depending on who can send a pre-play message in an employer-worker relationship, can be an effective tool for noncompliance prevention.
    :::

    </details>

-   Chapter 5: Exploring Reciprocation in the Alternation Game

    <details>

    <summary>Abstract</summary>

    ::: paper-description
    Reciprocity, as a form of coordination, is ubiquitous in social interactions. However, what does reciprocal behavior look like, and most importantly, why does reciprocal behavior exist in a non-cooperative, repeated interaction? We explore reciprocal behaviors in the Alternation Game (henceforth ‘AG’), a variant of the finitely repeated prisoner’s dilemma that a pair can be mutually beneficial by engaging in turn-taking behavior as a reciprocal behavior. Nash reasoning conjectures that reciprocation is impossible in the finitely repeated prisoner’s dilemma and AG, while a vast body of experimental studies contradicts this. Our exploratory study investigates two main reasons why Nash reasoning fails to predict: whether reciprocal behavior is driven by an individual’s concerns about others as well as own welfare (an aversion towards inequity posited by the Fairness model and an individual’s Social Value Orientation posited by the SVO Integrative Model), or an individual’s strategic concerns such as following an implicit tacit agreement in a context (Virtual Bargaining) or concerns about own reputation (Reputation Building). We conducted an online experiment with two different payoff conditions of AG that predictions from other-regarding preferences and strategic concerns differ. Our result shows various, instead of one, forms of reciprocal behaviors such as taking turns throughout the game (alternation), and cooperating in all rounds (cooperation). We also observe that a portion of participants do not reciprocate at all in the game (defection), which aligns with the finding in the finitely repeated prisoner’s dilemma. We find that a more cooperative environment does not lead to a rise in cooperation, thus cooperation in our finding is not context-dependent, which other-regarding preferences postulate. A portion of participants exhibit turn-taking behavior (in consecutive rounds or not) in both conditions. We find that they are virtual bargainers, instead of reputation builders.
    :::

    </details>

-   Chapter 6: Conclusion
::::
::::::::

</div>
</details>