---
title: "Book Reflection: At the Existentialist Cafe by Sarah Bakewell"
author: "Fendi Tsim"
date: "2024-03-02"
---

::: justify
Eight years ago, my English Literature Lecturer recommended me to read Sartre's 'Existentialism is Humanism'. I was fascinated by it and incorporated some of its ideas into my assignment. Later, with my lecturer's recommendation, my assignment became a chapter in a journal of literature and culture published by my college. 

At that time, Sartre's idea offered me, a twenty-year-old guy, some ground-breaking insights on how I think of living my life should be - existence precedes essence. 

Despite my 'philosophy' of how to live my life has departed from his idea, I still found myself roaming back to and intoxicating into it occasionally. 

Fortunately, I found this book in a public library. All the good old memories of reading Sartre's paper about 'Existentialism is Humanism' over and over come back instantly while reading it. 

I'm glad that I've picked up this book, and it definitely inspires me to read some works from Heidegger, Jaspers, Beauvoir, Kierkegaard as well as Merleau-Ponty. 

I'd to read Sartre's 'Being and Nothingness' in a cafe where he and Beauvoir had a profound discussion of their work about Existentialism.
:::
