---
title: "Sunday Morning Workout"
author: "Fendi Tsim"
date: "2024-06-23"
---

::: justify
I've been enjoying doing workouts on Sunday mornings.

Today I visited a local 24-7 gym at 5am. This is the first time I went there before 7am - I often wake up at around 5am, and went there at around 7:15am. To my surprise, there were a few people running on treadmills while some lifting up dumbbells.

Initially I planned to stay in bed, and try to get some rest. I was recovering from an illness, and only slept for four hours yesterday. My body, as well as my mind, kept telling me to stay at home. Yet, I do not want that - I'd rather get myself sweating a lot at the gym, then have some delicious food, and call it a day earlier than normal.

The tranquility inside the free weight area was comforting. It was a leg day for me Today. I managed to do a few reps of Barbell Squat, and eventually did heavier than last time. I left the gym with a smiley face - wondering how I could do that despite I was not in the best version I could be physically and mentally, and of course, what if I followed what my body and my mind have said.

I suspect what motivates me to doing workouts despite adversity is discipline. I'm in a bulking phrase, while I am trying to be active everyday. Sometimes I need to do what I do not want to do - possibly due to my laziness, or my over-thinking mind that persuades me how enormous a task would be and how incapable I was. Doing workouts on Sunday morning can be a haunting task - as most of us would definitely prefer to have a chill, and slow morning. Yet, like what I've seen from people around me, sometimes we just need to keep moving, and keep going, possibly due to in a pursuit of life goals, such as getting in shape, being healthier etc.

Keep going.
:::