---
title: "Book Reflection: Small Change by Dan Ariely"
author: "Fendi Tsim"
date: "2024-03-07"
---

::: justify
Been a long time since I read Dan’s book. When I learned Behavioral Economics eight years ago, I was intrigued by his books, as well as from Daniel Kahneman, Richard Thaler.

I admire the way he provides interesting real-life examples when explaining cognitive biases.

This book is, in my opinion, a great one to understand how we make financial decisions with cognitive biases - mental accounting, relativity, sunk cost fallacy etc.

My thought on these is whether it would apply in another domain in life: time. As the saying goes: ‘time is money’.

How time is framed as our own currency for trading - or a cost for opportunities, is ubiquitous in daily lives.

Of course, we cannot ‘save’ our time - a minute has gone is gone. It never comes back, and cannot be bought. However, we can make use of some biases in his book as a guidance of time management.

For instance, ‘sunk cost fallacy’ - we suffer the cost we paid (sunk cost) when we make a relevant decision. Of course, whatever happened happens - shall I continue on the same path, making a choice based on whatever (good or bad) that happened to me before?
:::
