---
title: "Word and its Meaning"
author: "Fendi Tsim"
date: "2024-03-15"
---

::: justify
Perhaps it’s due to a sheer volume of readings I had to do recently - I became more sensitive on selections of word, and often, wonder its underlying meaning.

Take ‘miss’ as an example. Growing up, I often used it to refer to a lady I am taking to. Then I realise it also refers to a situation that I fail my aim at - ‘hit or miss’. When a beloved is away from me, ‘miss’ becomes a verb - a way of describing my emotion as a result of being lost and found.

What about ‘remember’? It is, in fact, quite a delicate one. This word is often applied on living objects such as human beings and animals. If we decompose it into two parts: ‘re’ refers to doing an action like the verb it is attached to again. For instance, we have ‘rejoice’, ‘return’, ‘remove’, ‘retake’, ‘recur’, ‘rethink’ etc. The meaning of ‘member’ is a straightforward one: we are social animals, and each of us is a member within this social kingdom. As a result, ‘re-member’ can be interpreted as one of our members who was not a member before, becomes one of us again.

‘I remember you’, her son a mother who has dementia says to.

One last example requires a bit of imagination (which are abundant among us, isn’t it?), and it’s ‘proactive’. We have adjectives in similar forms like ‘active’ (which is an obvious one duh), ‘inactive’ (opposite of ‘active’), ‘reactive’ (a state when making a response). What about ‘proactive’ then?

Well, one simple way of interpreting it is ‘professionally active’. To me, ‘proactive’ is a cousin of ‘reactive’; it is an old attitude of living one’s life. Being active professionally is to taking matters seriously, as though we were dealing with it in a ‘professional’ setting.
:::
